import sorter.Sort;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public String getLibraryName() {
    	return "TestLib";
    }
    
    public static void main(String[] args) {
    	Sort sort = new Sort();
		int[] arr = {13, 7, 6, 45, 21, 9, 101, 102}; 
		int[] expectedSortedArray = {6, 7, 9, 13, 21, 45, 101, 102};
		
		int[] sorted = sort.insertion(arr);
		
		for(int i =0;i<sorted.length;i++) {
			System.out.print(sorted[i]+", ");
		}
		System.out.println();
	}
}
